meta_product_name: "Catch Up"
meta_title: "Catch Up - Got some films to Catch Up on?"
meta_description: "Missed out on one of the classics? Got recommended a film? Never miss a showing again with Catch Up! Find out about upcoming showings and get in contact with other Catchuppers to organise viewings together!"
meta_image: "cinematag.png" # should exist in `app/assets/images/`

